# Generated by Django 5.0.4 on 2024-04-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('image', models.ImageField(upload_to='collection/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
